ctl: improve error handling
hearth-rs/hearth pull request #134
Opened 2023-04-24 22:26 UTC by airidaceae

closes #131 

This pr still needs a lot of work before it can be merged. I would also like to have someone look over my use of error codes and make sure I used the right ones.

2023-04-25 00:49 UTC, marceline-cramer requested changes
Looks generally beautiful. A couple things:
- replace all `Result<(), CommandError>` with a generic type at the crate level: `type CommandResult<T> = Result<T, CommandError>`, then update all instances of that type to match.
- compact as much redundant code as possible into helper functions on the crate level. i want as little duplicated code as possible.

2023-04-25 00:49 UTC, marceline-cramer commented on crates/hearth-ctl/src/list_processes.rs
> +                            .to_command_error("finding peer", EX_PROTOCOL)?,
Make this peer provider function a crate-level helper function that fetches a peer from a daemon and returns this same error message. Replace all peer location operations with this function.

2023-04-25 00:49 UTC, marceline-cramer commented on crates/hearth-ctl/src/spawn_wasm.rs
> +            .to_command_error("retreiving WasmProcessSpawner", EX_UNAVAILABLE)?
retreiving -> retrieving

2023-04-25 00:49 UTC, marceline-cramer commented on crates/hearth-ctl/src/main.rs
> +        .to_command_error("connecting to hearth daemon", yacexits::EX_UNAVAILABLE)
capitalize the "h" in "Hearth"

2023-04-26 14:53 UTC, airidaceae commented
closes #77

2023-04-26 15:00 UTC, merged