Add `hearth-daemon` crate
hearth-rs/hearth pull request #158
Opened 2023-08-26 21:15 UTC by marceline-cramer

Paving the way for capability-based IPC. I migrated the stubs of the old IPC code into a new `hearth-daemon` crate and plugin. I also made it so that `hearth-core` finishes building plugins in the reverse order that they were added, so that we can say for sure that `hearth-daemon` adds its hook to `InitPlugin` before `InitPlugin` finalizes.

- core: reverse-ordered plugin finish()
- Add initial hearth-daemon crate
- ipc: remove daemon-only code
- server: use hearth-daemon for IPC
- client: use hearth-daemon for IPC
- ipc: copy Connection from network crate
- daemon: begin cap exchange on accept
- daemon: send IPC client root cap

2023-09-01 04:21 UTC, airidaceae requested changes
This all looks great. Pretty clean code and I made #162 for the only big issue I had with legibility. Id like the stuff I mentioned in this review to be considered before merging but its not all that much.

2023-09-01 04:21 UTC, airidaceae commented on crates/hearth-daemon/src/lib.rs
> +    pub fn on_accept(
Not sure on this after reading it a bit more. Up to you.

2023-09-01 04:21 UTC, airidaceae commented on crates/hearth-daemon/src/lib.rs
Overall looks really good. All of this is pretty legible code. Excited to use it in `hearth-ctl` :purple_heart:

2023-09-01 04:21 UTC, airidaceae commented on crates/hearth-ipc/src/lib.rs
struggling to read this code but I think it may just be sleepiness. Going to give it another try tomorrow.

2023-09-01 04:21 UTC, airidaceae commented on crates/hearth-ipc/src/lib.rs
ok nevermind i pulled up `hearth-deamon` and `hearth-ipc` up side-by-side and it makes sense now

2023-09-01 21:20 UTC, marceline-cramer commented on crates/hearth-daemon/src/lib.rs
> +                    "Socket is already in use. Another instance of Hearth may be running."
Would you be alright if I removed the warning log and just print that message when `DaemonPlugin` panics on `unwrap()`? It's in a dedicated Tokio thread so it won't affect the rest of the runtime, it's just up to ergonomics of a log warning versus a panic message.

2023-09-09 21:35 UTC, airidaceae commented on crates/hearth-daemon/src/lib.rs
> +                    "Socket is already in use. Another instance of Hearth may be running."
I think that would work well for now. In the future id like to exit gracefully and map panics to an error-level log message.

2023-09-10 01:49 UTC, airidaceae approved these changes

2023-09-10 05:26 UTC, merged