Add `hearth-terminal` plugin
hearth-rs/hearth pull request #161
Opened 2023-08-31 19:36 UTC by marceline-cramer

This PR exposes the `rend3-alacritty` to Hearth guests as a terminal factory service that creates guest-accessible instances of terminals.

I've made major changes to the `hearth_core::utils` module by abstracting native code that takes ownership of and executes native processes using a `ProcessRunner` trait. I also made a generalization of native processes that only accept JSON messages of one type using the `SinkProcess` trait, which has a blanket implementation for `ProcessRunner`. I also made `RequestResponseProcess` a specialization of `SinkProcess` that receives messages and sends responses back. Finally, I transformed `RequestResponseService` into `ServiceRunner: ProcessRunner` that generically implements `Plugin`. I've updated `hearth-cognito` and `hearth-fs` with the `utils` changes.

The `utils` changes were necessary because the terminal code needs to both add a render routine to `Rend3Plugin` AND register a terminal factory service, meaning that `TerminalPlugin` can't use the `Plugin` blanket implementation from `ServiceRunner`. Each individual receiver of `TerminalUpdate` also needs to be a dedicated process that receives messages but does not send messages back, necessitating the creation of the `SinkProcess` trait. To deduplicate code I then made `RequestResponseProcess` a specialization of `SinkProcess` and made a new `ProcessRunner` trait to abstract both (and all future) use-cases.

Please give this a look-over and let me know if anything needs explanations, commenting, refactoring, or anything else.

2023-09-09 07:23 UTC, siltyy requested changes
Looks fine to merge once the line I marked gets fixed.

2023-09-09 21:40 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
cognito is pretty massive. I'm not familiar enough with the code to know how this could be done but it may be good to separate it out into more files.

2023-09-09 21:50 UTC, siltyy commented on crates/hearth-cognito/src/lib.rs
Barring any technical limitations, that sounds reasonable to me. The `lib.rs` is pretty large and some more compartmentalization would help Cognito's approachability imo.

2023-09-09 21:58 UTC, marceline-cramer commented on crates/hearth-cognito/src/lib.rs
Yeah, this also sounds good to me. I can tack it onto the Flue PR, or we could do it in a separate issue. Thoughts?

2023-09-09 22:06 UTC, marceline-cramer commented on crates/hearth-cognito/src/lib.rs
Also, to be more specific: I think I'd decouple the *Abi structs from all the plugin and factory stuff, so that lib.rs contains Hearth integration code and the new "abi.rs" file would contain low-level Wasm integration code only.

2023-09-09 22:09 UTC, marceline-cramer commented on crates/hearth-terminal/src/lib.rs
> +                inner.send_input(&input);
Done.

2023-09-09 22:10 UTC, siltyy commented on crates/hearth-cognito/src/lib.rs
Either way, it's probably best to not tackle it in this PR.

2023-09-09 22:37 UTC, airidaceae requested changes
working on getting some stuff running to see if its an issue on my end but heres some stuff for now

2023-09-09 22:37 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
I think its a large enough change that it deserves its own PR. could also use it to clean up any cognito clippy suggestions that have been hanging around for a while.

2023-09-09 22:37 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +    async fn on_message(&mut self, request: &mut RequestInfo<'_, Self::Message>) {
i think this code is really pretty and it makes me happy :)

2023-09-09 22:37 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +        let FactoryRequest::CreateTerminal(state) = &request.data;
i love this

2023-09-09 22:37 UTC, airidaceae commented on crates/hearth-types/src/lib.rs
> +// Terminal protocol.
make this into a doc comment

2023-09-09 22:37 UTC, airidaceae commented on crates/rend3-alacritty/examples/demo.rs
> +            ..Default::default()
i have never seen this syntax before. cool stuff. may end up using this in the Defaults issue we were talking about with the config file

2023-09-09 22:38 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
I think its a large enough change that it deserves its own PR. could also use it to clean up any cognito clippy suggestions that have been hanging around for a while.

2023-09-09 22:50 UTC, marceline-cramer commented on crates/hearth-cognito/src/lib.rs
#167.

2023-09-09 22:50 UTC, airidaceae commented
> working on getting some stuff running to see if its an issue on my end but heres some stuff for now

the stuff on my end was not broken! yipee!!

2023-09-09 23:19 UTC, airidaceae approved these changes

2023-09-09 23:19 UTC, airidaceae commented
looks great :)

2023-09-10 18:46 UTC, siltyy approved these changes

2023-09-10 18:48 UTC, merged