Flue
hearth-rs/hearth pull request #170
Opened 2023-09-17 18:56 UTC by marceline-cramer

Substitutes Hearth's in-house process store implementation with the still in-house but out-of-repo "flue" crate. Benefits:

- more speed (flue is much more efficient)
- more ergonomic host-side APIs (featuring lifetimes instead of raw handles)
- mailbox support
- more concise code host- and guest-side
- registries as processes
- testing and securing of low-level process mechanics are outsourced to the flue repo

As always, please let me know if anything could be better documented or refactored! This PR is really large and there's a lot going on. There's no rush.

2023-10-24 03:46 UTC, airidaceae requested changes
I have done it. The beast conquered. The dragon slain!

sillyness aside, I missed a lot. Id like to help update things once we've pulled in the flue API changes I think it will help me catch some of the issues I've missed. Before we merge it in I will also likely do another full review. I was getting sleepy near the end and I could feel the quality of my reviews going down.

2023-10-24 03:46 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
> +    fn dec_ref(&self, handle: u32) -> Result<()> {
type aliases would be helpful here
Will these be fixed by the flue pr adds type aliases?

2023-10-24 03:46 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
> +    fn dec_ref(&self, handle: u32) -> Result<()> {
Same applies to all the other functions

2023-10-24 03:46 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
lots of `usize`s and `u32`s here. It may be a good idea to make type aliases for most of those. We also convert between `u32`s and `usize`s a lot. We may need some comments as to why we are using each one.

2023-10-24 03:46 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
lets add a `#![warn(missing_docs)]` and add more docs to this file. I think its pretty important that this api is easy to use.

2023-10-24 03:46 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
>  /// This contains all script-accessible process-related stuff.
"stuff" is not very descriptive for a doc comment

2023-10-24 03:46 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
Same deal as cognito but arguably more important. Add more doc comments and a #![warn(missing_docs)]`

2023-10-24 03:46 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +pub struct Process(u32);
I think a different name would be better for this. Process implies that its the actual process. not its handle.

2023-10-24 03:46 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +impl Clone for Process {
Document why we need to implement these. Should also justify the use of unsafe code.

this comment applies to all of the functions that do this

2023-10-24 03:46 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +pub struct Mailbox(u32);
Same thing here as `Process`.

2023-10-24 03:50 UTC, airidaceae commented
I mentioned a change I wanted to the flue docs in the flue PR. I cant seem to find it here rn. Ill look again tomorrow and if I cant find it we just wont worry about it.

2023-10-24 18:48 UTC, airidaceae commented on crates/hearth-client/src/main.rs
> +    let _root_cap = match root_cap.await {
I don't actually know if this is neccesary

2023-10-24 18:49 UTC, airidaceae commented on crates/hearth-client/src/main.rs
> +    let _root_cap = match root_cap.await {
This pattern is used in a few place and tbh i think its pretty clear

2023-10-24 23:19 UTC, marceline-cramer commented on crates/hearth-client/src/main.rs
> +    let _root_cap = match root_cap.await {
I think so. Freeing the cap is a relic of the old capability code, and Flue-based capabilities cleanly drop.

2023-10-24 23:21 UTC, marceline-cramer commented on crates/hearth-core/src/lib.rs
>  // pub mod pubsub;
The `process` module definition is still around, it just got moved and the docs changed.

2023-10-24 23:25 UTC, marceline-cramer commented on crates/hearth-core/src/process.rs
> +        let pid = self
PIDs are guessable but they're only available or used in the log messages and in the upcoming debug system that would be a big no-no to pass to untrusted code. Processes also can't access their own PIDs directly.

2023-10-24 23:26 UTC, airidaceae commented on crates/hearth-core/src/process.rs
> +        let pid = self
Yup. lets add a comment making sure that people know that

2023-10-24 23:32 UTC, marceline-cramer commented on crates/hearth-core/src/process.rs
> +pub struct ProcessInfo {
Makes sense, on it.

2023-10-24 23:32 UTC, marceline-cramer commented on crates/hearth-core/src/process.rs
> +        let pid = self
Can do.

2023-10-24 23:35 UTC, airidaceae requested changes

2023-10-24 23:35 UTC, airidaceae commented on crates/hearth-core/src/registry.rs
> +    pub fn add(&mut self, name: String, mailbox: &Mailbox) {
Make it clear why the add function is on the builder and not the Registry. May honestly want to change the function name too because it kinda sounds like you're adding a new registry.

2023-10-24 23:51 UTC, marceline-cramer commented on crates/hearth-core/src/runtime.rs
> +        let mut info = ProcessInfo::default();
Yeah, I wrote this before I came up with that macro and forgot to use it here.

2023-10-24 23:52 UTC, airidaceae commented on crates/hearth-core/src/lib.rs
>  // pub mod pubsub;
im referring to the pubsub module

2023-10-25 03:58 UTC, marceline-cramer commented on crates/hearth-core/src/lib.rs
>  // pub mod pubsub;
Ah yeah, if we do reinstate it, it should go into `utils`.

2023-10-25 04:03 UTC, marceline-cramer commented on crates/hearth-core/src/process.rs
> +impl Drop for ProcessIdentity {
I don't remember doing that for the Drop message, I think I initially meant it just to compartmentalize process data.

2023-10-25 04:03 UTC, marceline-cramer commented on crates/hearth-core/src/process.rs
> +pub struct Process {
Done.

2023-10-25 04:05 UTC, marceline-cramer commented on crates/hearth-core/src/registry.rs
> +    pub fn add(&mut self, name: String, mailbox: &Mailbox) {
It doesn't have to refer to a process's parent mailbox. I purposefully decoupled it from the `Process` type for the sake of decoupled code.

Process has `borrow_parent()` to get a reference to its parent mailbox.

2023-10-25 04:21 UTC, marceline-cramer commented on crates/hearth-core/src/process.rs
> +/// Metadata of a running process with data distinguishing it from other processes.
I went through with this.

2023-10-25 04:24 UTC, marceline-cramer commented on crates/hearth-core/src/utils.rs
> +                None => break,
Added comments, what do you think?

2023-10-25 04:24 UTC, marceline-cramer commented on crates/hearth-cognito/examples/run_wasm.rs
> +    let registry = parent.borrow_table().wrap_handle(registry).unwrap();
Improved. Thoughts?

2023-10-25 04:25 UTC, airidaceae commented on crates/hearth-core/src/lib.rs
>  // pub mod pubsub;
got it. Issue?

2023-10-25 04:26 UTC, marceline-cramer commented on crates/hearth-core/src/lib.rs
>  // pub mod pubsub;
Nah, I think we should do it on demand whenever we need it in a feature.

2023-10-25 04:27 UTC, airidaceae commented on crates/hearth-core/src/process.rs
> +impl Drop for ProcessIdentity {
Ah ok. Maybe you just mentioned it as an added benefit

2023-10-25 04:27 UTC, marceline-cramer commented on crates/hearth-cognito/src/lib.rs
> +    fn dec_ref(&self, handle: u32) -> Result<()> {
So the issue is that these are being used as wasmtime function callbacks, which NEED to be one of the types that wasmtime implements `WasmTy` for: https://docs.rs/wasmtime/latest/wasmtime/trait.WasmTy.html

2023-10-25 04:29 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +pub struct Mailbox(u32);
I disagree in this case because `Mailbox` directly corresponds to a single host-side `Mailbox` object and controls its lifetime.

2023-10-25 04:31 UTC, marceline-cramer commented on crates/hearth-core/src/connection.rs
Can it wait until we do connection code properly?

2023-10-25 04:32 UTC, airidaceae commented on crates/hearth-core/src/lib.rs
>  // pub mod pubsub;
awesome possum :D

2023-10-25 04:32 UTC, airidaceae commented on crates/hearth-core/src/connection.rs
yes :)

2023-10-25 04:35 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +pub struct Process(u32);
What about "Capability"?

Should also edit the docs to "A capability to a route." instead?

2023-10-25 04:40 UTC, marceline-cramer commented on crates/hearth-cognito/src/lib.rs
Sure, can do. These APIs are only used by the guest, but yeah, it'd help out binding authors and whoever is editing the functions themselves.

2023-10-25 04:41 UTC, airidaceae commented on crates/hearth-core/src/process.rs
> +    /// Spawns a new process in this factory's [PostOffice].
I think that its important that we mention directly the table because this method exists and needs to be defined in relation to `spawn_with_table`

2023-10-25 04:41 UTC, airidaceae commented on crates/hearth-core/src/process.rs
> +    /// Spawns a new process.
make a new comment for this. resolving

2023-10-25 04:54 UTC, marceline-cramer commented on crates/hearth-init/src/lib.rs
> +                    tracing::error!("expected message, got {:?}", signal);
I think I may go ahead and add an `on_down` method to the trait that defaults to having no body, and call it in this. What do you think?

2023-10-25 05:02 UTC, airidaceae commented on crates/hearth-core/src/process.rs
Great job here. Docs look great.

2023-10-25 05:02 UTC, airidaceae commented on crates/hearth-cognito/examples/run_wasm.rs
> +    let registry = parent.borrow_table().wrap_handle(registry).unwrap();
much better.

2023-10-25 05:08 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +pub struct Process(u32);
Yeah I like that

2023-10-25 05:08 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +pub struct Mailbox(u32);
Ok. Just add a doc comment then

2023-10-25 05:18 UTC, airidaceae commented on crates/hearth-core/src/registry.rs
> +    pub fn add(&mut self, name: String, mailbox: &Mailbox) {
ok awesome.

2023-10-25 05:25 UTC, airidaceae commented on crates/hearth-core/src/runtime.rs
> +        let info = ProcessMetadata {
so clean.....

2023-10-25 05:25 UTC, airidaceae commented on crates/hearth-core/src/utils.rs
> +                None => break,
clears it up :)

2023-10-25 05:35 UTC, airidaceae commented on crates/hearth-cognito/src/lib.rs
> +    fn dec_ref(&self, handle: u32) -> Result<()> {
got it.

2023-10-25 06:09 UTC, airidaceae commented on crates/hearth-init/src/lib.rs
> +                    tracing::error!("expected message, got {:?}", signal);
That would be upon receiving the down signal from a process that is being monitored right? I think that sounds good.

2023-10-25 06:09 UTC, marceline-cramer commented on crates/hearth-init/src/lib.rs
> +                    tracing::error!("expected message, got {:?}", signal);
Can do, I'll get on that when I can.

2023-10-25 06:12 UTC, airidaceae commented
This is temporarily blocked while we wait for upstream api changes from [Flue's docs PR](https://github.com/hearth-rs/flue/pull/1)

2023-10-29 21:57 UTC, marceline-cramer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Flue PR](https://trello.com/c/BJptQXix/9-flue-pr)

2023-10-31 19:11 UTC, airidaceae commented on crates/hearth-core/src/process.rs
> +    pub pid: usize,
lets make a type alias here

2023-10-31 19:16 UTC, airidaceae commented on crates/hearth-init/src/lib.rs
> +                    tracing::error!("expected message, got {:?}", signal);
looks great!!

2023-11-02 06:19 UTC, airidaceae requested changes

2023-11-02 06:19 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +    }
why dont we set `meta.name` here?

2023-11-02 06:19 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +        let mut meta = cargo_process_metadata!();
could we replace this with a call to `Self::get_process_metadata()`? Should allow us to get rid of the `mut`

2023-11-02 18:20 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +    }
I see that we have the constant NAME and it claims that it overwrites `meta.name` but I don't actually see the code where that happens.

2023-11-02 18:23 UTC, marceline-cramer commented on crates/hearth-terminal/src/lib.rs
> +    }
It occurs in the blanket `Plugin` implementation for `ServiceRunner` in `hearth_core::utils`.

2023-11-02 18:24 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +    }
oh i see. its done in the finalize function. That overwriting behavior only happens for plugins then.

2023-11-02 18:27 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +        let mut meta = cargo_process_metadata!();
nope we cant because `get_process_metadata()` is for the plugin whereas `meta` here is for an instance of the plugin

2023-11-02 18:29 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +        let mut meta = cargo_process_metadata!();
lets add some comments making this distinction clear.

2023-11-02 18:29 UTC, airidaceae commented on crates/hearth-terminal/src/lib.rs
> +    }
going to resolve this as it does not seem useful or necessary.

2023-11-02 18:41 UTC, airidaceae commented
just updated debug draw. The `meta.description`s may need to be tweaked a bit @marceline-cramer

2023-11-02 18:46 UTC, marceline-cramer reviewed
This looks great, good job!

2023-11-02 18:51 UTC, marceline-cramer commented
Ok, I just need your last review on all of the docs and hanging unresolved conversations. In the meantime, I'll add the mailbox group polling to the epoch interrupt.

2023-11-02 18:52 UTC, marceline-cramer commented on crates/hearth-terminal/src/lib.rs
> +        let mut meta = cargo_process_metadata!();
Done.

2023-11-03 01:37 UTC, airidaceae requested changes
flue review part 2 electric boogaloo

2023-11-03 01:37 UTC, airidaceae commented on crates/hearth-init/src/lib.rs
> +                let _ = self.callback.send(cap);
why dont we handle the potential error?

2023-11-03 01:37 UTC, airidaceae commented on crates/hearth-types/src/lib.rs
> +        const LINK = 1 << 1;
Change this to `MONITOR`

2023-11-03 01:37 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +    Unlink {
This should be `Down`

2023-11-03 01:37 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +    pub fn make_capability(&self, perms: Permissions) -> Capability {
if we change the other `make_capability` make sure we change this one too.

2023-11-03 01:37 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +    pub fn link(&self, subject: &Capability) {
this should be changed to monitor.

2023-11-03 03:34 UTC, marceline-cramer commented on crates/hearth-client/src/window.rs
> +use rend3::{InstanceAdapterDevice, Renderer};
I'll get rid of it.

2023-11-03 03:35 UTC, airidaceae commented on crates/hearth-client/src/window.rs
> +use rend3::{InstanceAdapterDevice, Renderer};
feel free to resolve when you're done.

2023-11-03 03:53 UTC, marceline-cramer commented on crates/hearth-cognito/src/lib.rs
>      async fn from_id(&mut self, memory: GuestMemory<'_>, id_ptr: u32) -> Result<u32> {
I'll take `load_by_id`.

2023-11-03 04:04 UTC, marceline-cramer commented on crates/hearth-cognito/src/lib.rs
> +    fn make_capability(&self, handle: u32, perms: u32) -> Result<u32> {
Processes only possess a single table and Wasm processes can't access each other's tables, so there's nothing more we could represent in the ABI here.

2023-11-03 04:07 UTC, marceline-cramer commented on crates/hearth-core/src/process.rs
> +pub type ProcessId = usize;
`.0` is annoying.

2023-11-03 04:08 UTC, marceline-cramer commented on crates/hearth-core/src/process.rs
> +pub type ProcessId = usize;
If we end up using `ProcessId` more than we do now then that could come in handy though.

2023-11-03 04:08 UTC, marceline-cramer commented on crates/hearth-init/src/lib.rs
> +                let _ = self.callback.send(cap);
No idea.

2023-11-03 04:27 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +    pub fn make_capability(&self, perms: Permissions) -> Capability {
Not changing, so not touching.

2023-11-03 05:35 UTC, airidaceae approved these changes
awesome possum.

2023-11-03 05:36 UTC, merged