Debug draw
hearth-rs/hearth pull request #182
Opened 2023-10-20 00:27 UTC by marceline-cramer

Adds debug draw lines to Hearth! We can now draw arbitrary 3D lines!

Bonus:
- Reuses existing GPU memory buffers between draws in `rend3-alacritty`
- Gets rid of the hardcoded cube in the client
- Uses `BaseRenderGraphIntermediateState` in `hearth-rend3::RoutineInfo` so that custom rend3 routines can share the depth buffer used by rend3's default PBR pass
- Fixes depth buffer management in `rend3-alacritty`

2023-10-24 21:36 UTC, ten3roberts requested changes
I have given my input given what I know.

I am not yet too familiar with Hearths source code, but I am getting there; but in the meantime my advice will be more general

2023-10-24 21:55 UTC, marceline-cramer commented on crates/hearth-debug-draw/src/lib.rs
> +                            color: ((v.color[2] as u32) << 16)
I think that maybe I'll make a `struct Color(pub u32);` type in `hearth-types` along with some handy conversion methods, since we're representing colors in the message protocols in `hearth-types`, too. Ha, that may even get me to add custom terminal colors to the terminal protocol, too.

2023-10-24 21:57 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +        let capacity = 128;
Makes sense, can do! Thank you for pointing that out.

2023-10-24 21:58 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +            while self.capacity < data.len() as u64 {
I didn't think of that! Will fix.

2023-10-24 22:05 UTC, marceline-cramer commented on crates/hearth-debug-draw/src/lib.rs
> +        for (id, update) in updates {
Ahhhh crap, while considering that I did also just realize that if the routine processes a `Hide` message in the same frame as a `Contents` message, they'll shadow each other since the `updates` hash map is overwritten by the latest key.

I think I'll go ahead and integrate `.drain().into_group_map()` and rework the update loop to pop queued update messages until it's empty or until every property has been updated.

2023-10-24 22:59 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +        let capacity = 128;
Hmm, after thinking about it a bit: are there any reasonable defaults we can use in specific use-cases? This initial capacity has to be host-defined somewhere, so all we have to choose the initial capacity is the element size. Maybe we should have a hard-coded initial capacity in bytes (say, 1024), and then divide by the element size, rounding up, to get the initial capacity.

2023-10-24 23:13 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +pub struct GpuVector<T> {
So, this really shouldn't be here to begin with, since `rend3-alacritty` should only really have to do with terminal rendering, but since it needs the same dynamic GPU buffer pattern that debug draw does, I figure I'd integrate it here and then use it as a dependency of the debug draw crate. I did this to avoid having a dependency on some GPU utils crate that I figure wouldn't have much in it anyways.

If the concern is that `GpuVector` and `DynamicMesh` are in the same module as some `rend3-alacritty`-only definitions, I could definitely move those to another module.

What do you think?

2023-10-28 18:56 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +pub struct GpuVector<T> {
I have an idea:

There are two reasons for why I made `rend3-alacritty` a separate crate originally:
1. it made it easy to develop a standalone demo without supporting Hearth infrastructure.
2. it allowed `rend3-alacritty` to be independently published on crates.io and used by other people.

We can still replicate the standalone demo in the `hearth-terminal` by bypassing anything relating to the Hearth runtime API and directly using the terminal renderer structs just like we do in the existing demo. I don't think that there's much of a chance that anyone would find a use for specifically embedding Alacritty into rend3 like we have.

So, we could merge `rend3-alacritty` into the `hearth-terminal` crate, and move its low-level helper structs like `GpuVector` into `hearth-rend3` instead so that `hearth-debug-draw` and future renderer node plugins can break the dependency on the terminal rendering modules.

@airidaceae what do you think?

2023-10-29 17:29 UTC, airidaceae commented on crates/rend3-alacritty/src/gpu.rs
> +pub struct GpuVector<T> {
sounds good to me!

2023-10-29 17:32 UTC, airidaceae commented on crates/rend3-alacritty/src/gpu.rs
> +pub struct GpuVector<T> {
lets make a comment on #169 explaining the plan and then go forward with this. Lets not worry about it on this PR.

2023-10-29 19:03 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +pub struct GpuVector<T> {
Updated #169 and opened #188.

2023-10-30 04:21 UTC, airidaceae requested changes
Looks pretty good :)

2023-10-30 04:21 UTC, airidaceae commented on crates/rend3-alacritty/src/gpu.rs
> +    pub fn len(&self) -> u64 {
Clippy warning here. Not sure if this is needed for our use case but it may be worth looking at.

2023-10-30 04:21 UTC, airidaceae commented on crates/rend3-alacritty/src/lib.rs
>      pub fn update(&mut self) -> bool {
explain the purpose of the return value

2023-10-30 10:35 UTC, ten3roberts commented on crates/rend3-alacritty/src/gpu.rs
> +        let capacity = 128;
I'd say since it grows automatically, we could make it zero sized, or if that is not possible, just a single element.

2023-10-30 22:18 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +        let capacity = 128;
Zero sized works, at least on my machine (TM).

2023-10-30 22:25 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +    pub fn len(&self) -> u64 {
It was easy so I did it.

2023-10-31 17:30 UTC, marceline-cramer commented on crates/rend3-alacritty/src/gpu.rs
> +        let capacity = 128;
Done.

2023-10-31 23:36 UTC, airidaceae approved these changes

2023-11-01 13:14 UTC, ten3roberts approved these changes
Looks good to me now, I feel like my points have been properly heard and adequately addressed, which is always nice 😊 

I suppose we then just need to get the tests to pass and then for the rest of the team to agree and approve it

2023-11-01 14:32 UTC, airidaceae commented
Sadly unit tests haven't been passing for a while. Its some old process stuff that will be completely fixed by #170

2023-11-01 15:27 UTC, merged