Window service
hearth-rs/hearth pull request #194
Opened 2023-11-04 17:21 UTC by marceline-cramer

- types: add window module
- types: fix winit usage
- client: WIP WindowPlugin

2023-11-13 00:36 UTC, airidaceae requested changes

2023-11-13 00:36 UTC, airidaceae commented on crates/hearth-client/src/window.rs
> +            camera: self.camera.clone(),
clippy

2023-11-13 00:36 UTC, airidaceae commented on crates/hearth-client/src/window.rs
>  struct Window {
docs here might be nice

2023-11-13 00:36 UTC, airidaceae commented on crates/hearth-types/src/window.rs
> +    Subscribe, // and hit that bell
dont think i wouldn't see this :eye: :eye:

2023-11-13 00:37 UTC, marceline-cramer commented on crates/hearth-types/src/window.rs
> +    Subscribe, // and hit that bell
Can it stay? 🥺

2023-11-13 00:38 UTC, airidaceae commented on crates/hearth-types/src/window.rs
> +    Subscribe, // and hit that bell
..............yes

2023-11-16 05:25 UTC, airidaceae requested changes

2023-11-18 03:06 UTC, marceline-cramer commented
There's a bug where the `kindling-window-test` event subscriber mailbox is getting immediately signaled as down to the window service even though it definitely is not. Not sure how to minimally reproduce. Help would be appreciated.

2023-11-18 04:38 UTC, marceline-cramer commented
Fixed it: https://github.com/hearth-rs/flue/pull/17

2023-11-24 06:32 UTC, marceline-cramer commented on crates/hearth-client/src/window.rs
We've decided to do this as part of #222.

2023-11-25 20:53 UTC, airidaceae requested changes

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +    /// to the subscriber with the send perm for notifying it.
This comment is clunky. Heres my idea

> A mutex-locked set of subscribers. Each entry maps a zero permission capability as the index to a send-only capability for notifying.

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +    subscribers: Mutex<HashMap<usize, CapabilityHandle>>,
flue 0.2.1 will make it so we can use a `CapabilityHandle` as the index here too

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +    _phantom: PhantomData<T>,
document why this is needed. What is the phantom ownership here of.

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +    }
shouldn't be needed in flue 0.2.1

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +            error!("cap given to {} pubsub doesn't permit send", name);
capitalize this C and spell out "Capability" fully. this matches our existing error logging conventions.

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +                error!("error deserializing {}: {:?}", name, err);
The error log for this will look like
`Error: error deserializing {}: {}`
Which is clunky and also breaks existing error logging conventions.

lets change this to
`error!("failed to deserialize {}: {:?}", name, err);`

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +pub struct PubSub<T> {
I absolutely love the implementation of this pattern here. It looks great and works really really well.

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +    /// Removes a subscriber. Does nothing if the cap is not already subscribed.
may print an `info` or `warn` log message id the cap is not already subscribed

2023-11-25 20:53 UTC, airidaceae commented on core/runtime/src/utils.rs
> +        }
In flue we use an async move in situations like this. Im not sure if that's needed here but I figured I should bring up the idea.

2023-11-25 20:53 UTC, airidaceae commented on core/schema/src/window.rs
> +// TODO port DeviceId?
Open a help-wanted discussion issue for potential WindowEvent features that we may want going forward.

2023-11-25 20:53 UTC, airidaceae commented on core/schema/src/window.rs
> +    // TODO: rename
Is this our TODO comment or theirs?
Delete it if its theirs.

2023-11-25 20:53 UTC, airidaceae commented on main/client/src/window.rs
>  pub enum WindowRxMessage {
The standard now is WindowRequest. On line 465 you refer to it as such. Lets update this to fit with the new terminology.

2023-11-25 20:53 UTC, airidaceae commented on main/client/src/window.rs
>  pub enum WindowRxMessage {
Same should apply to WindowTxMessage. Cant comment on it due to github rules.

2023-11-25 20:53 UTC, airidaceae commented on main/client/src/window.rs
>  pub enum WindowRxMessage {
oh wait nevermind this is the host side :3

2023-11-25 20:53 UTC, airidaceae commented on main/client/src/window.rs
>      _directional_handle: rend3::types::ResourceHandle<rend3::types::DirectionalLight>,
can we import DirectionalLight (and maybe Resource handle) to clean up this type? 

We use DirectionalLight elsewhere which is why I think we should certainly bring that one in.

2023-11-25 20:53 UTC, airidaceae commented on main/client/src/window.rs
> +                    warn!("subscribe messsage is missing capability");
Capital S

2023-11-25 20:53 UTC, airidaceae commented on main/client/src/window.rs
> +                    warn!("unsubscribe messsage is missing capability");
Capital U

2023-11-25 20:53 UTC, airidaceae commented on main/client/src/window.rs
> +fn conv_keycode(code: winit::event::VirtualKeyCode) -> VirtualKeyCode {
this sucks lol

2023-11-25 20:53 UTC, airidaceae commented on main/client/src/window.rs
> +fn conv_keycode(code: winit::event::VirtualKeyCode) -> VirtualKeyCode {
sucks that we have to do it*

2023-11-25 23:14 UTC, marceline-cramer commented on core/runtime/src/utils.rs
> +        }
I'd like to keep it this way so that a single Tokio task sending multiple notifications in sequence maintains the sequence of the messages by `await`ing each use of `notify`.

2023-11-25 23:15 UTC, marceline-cramer commented on core/schema/src/window.rs
> +    // TODO: rename
Oops, nice catch.

2023-11-25 23:24 UTC, marceline-cramer commented on core/runtime/src/utils.rs
> +    /// Removes a subscriber. Does nothing if the cap is not already subscribed.
That's super easy to trigger from guest-side code either accidentally or on purpose, so I'm not sure if the clarity would be worth the potential log spam.

2023-11-26 00:01 UTC, airidaceae commented on core/runtime/src/utils.rs
> +                error!("error deserializing {}: {:?}", name, err);
change this to debug level

2023-11-26 00:02 UTC, airidaceae commented on core/runtime/src/utils.rs
> +            error!("cap given to {} pubsub doesn't permit send", name);
change this to debug level

2023-11-26 00:12 UTC, marceline-cramer commented on core/runtime/src/utils.rs
> +                error!("error deserializing {}: {:?}", name, err);
OH WAIT. THIS ISN'T A DESERIALIZE ISSUE. it's a serialize issue, and yeah, if a host-side data structure is failing to serialize, that IS something we'd want to log as an error.

2023-11-26 00:14 UTC, airidaceae commented on core/runtime/src/utils.rs
> +        }
sounds good

2023-11-26 00:14 UTC, airidaceae commented on core/runtime/src/utils.rs
> +                error!("error deserializing {}: {:?}", name, err);
gotcha

2023-11-27 04:02 UTC, airidaceae commented on core/runtime/src/utils.rs
> +                error!("failed to serialize {}: {:?}", name, err);
capital F

2023-11-27 04:52 UTC, airidaceae commented on core/runtime/src/utils.rs
> +    /// Removes a subscriber. Does nothing if the cap is not already subscribed.
ok

2023-11-29 03:49 UTC, airidaceae approved these changes

2023-11-29 03:50 UTC, merged