wasm: initialize ProcessMetadata from guest export
hearth-rs/hearth pull request #237
Opened 2023-11-20 04:51 UTC by marceline-cramer

Closes #171.

- [x] macros: replace ABI AsMut with GetAbi
- [x] wasm: add GetAbi
- [x] guest: add export_metadata macro
- [x] wasm: add metadata init phase
- [x] kindling-init: add export_metadata
- [x] kindling-panic-test: add export_metadata
- [ ] wasm: document ProcessData enum
- [ ] wasm: document MetadataAbi
- [ ] wasm: clean up and document metadata init code flow
- [ ] guest: document export_metadata

2023-12-10 20:12 UTC, airidaceae requested changes
Looking pretty good. Make sure that we merge main and see if we can get CI passing

2023-12-12 03:36 UTC, marceline-cramer commented on plugins/wasm/src/lib.rs
>  impl ProcessData {
i forgor 💀

2023-12-13 18:22 UTC, marceline-cramer commented
@airidaceae hmm, should we log a warning if a process doesn't export metadata?

2023-12-13 18:24 UTC, airidaceae commented
> should we log a warning if a process doesn't export metadata?
I can see that being useful when trying to track down an issue. Should also give some good feedback to guest side devs. Go for it.

2023-12-13 18:28 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +/// Exports this guest's process metadata using its Cargo package configuration.
Actually, I think this is technically correct? We are exporting the process metadata belonging to this guest. Could we make this more clear?

2023-12-13 18:30 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +/// Exports this guest's process metadata using its Cargo package configuration.
In that case my confusion is more on "this guest." Can you clarify what you mean by that?

2023-12-13 18:32 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +/// Exports this guest's process metadata using its Cargo package configuration.
Since the metadata exporting is deterministic per Wasm module, I think that I really mean "this WebAssembly module's process metadata". How does that sound?

2023-12-13 18:34 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +/// Exports this guest's process metadata using its Cargo package configuration.
I think the confusion came from how we use the word "guest" elsewhere. That is much more clear, go for it.

2023-12-13 19:04 UTC, airidaceae approved these changes

2023-12-13 19:06 UTC, merged