Add `hearth-time`
hearth-rs/hearth pull request #239
Opened 2023-11-20 06:16 UTC by marceline-cramer

Closes #234.

2023-11-25 23:09 UTC, airidaceae commented
lets add follow up issues to implement easy sleep functions in the kindling common crate stuff

2023-11-25 23:09 UTC, marceline-cramer commented
> lets add follow up issues to implement easy sleep functions in the kindling common crate stuff

or we could leave a comment in that issue

2023-11-25 23:10 UTC, airidaceae commented
works for me

2023-11-25 23:45 UTC, airidaceae requested changes

2023-11-25 23:45 UTC, airidaceae commented on core/runtime/src/utils.rs
> +pub trait RunnerContext<'a> {
looks good. I was thinking about this in the past.

2023-11-25 23:45 UTC, airidaceae commented on main/client/src/main.rs
> +    builder.add_plugin(hearth_time::TimePlugin::default());
clippy

2023-11-25 23:45 UTC, airidaceae commented on main/server/src/main.rs
> +    builder.add_plugin(hearth_time::TimePlugin::default());
clippy

2023-11-25 23:45 UTC, airidaceae commented on plugins/terminal/src/lib.rs
> +            caps: vec![child],
this is super nice

2023-11-25 23:45 UTC, airidaceae commented on plugins/time/src/lib.rs
> +            debug!("sleep request has reply address");
Capital S 
Also i don't think this message makes sense
"Sleep request has no reply address"?
This may be worth of an error status too.

2023-11-25 23:45 UTC, airidaceae commented on plugins/time/src/lib.rs
> +/// response.
could you work on the wording for this comment?

2023-11-25 23:45 UTC, airidaceae commented on plugins/time/src/lib.rs
This is some great code.

2023-11-25 23:51 UTC, marceline-cramer commented on plugins/time/src/lib.rs
> +            debug!("sleep request has reply address");
Oops, that was a typo.

2023-11-25 23:57 UTC, marceline-cramer commented on plugins/time/src/lib.rs
> +            debug!("sleep request has reply address");
I've been using `debug` for "failed to parse" or "no reply address" historically, including in `hearth_runtime::utils`. Still wanna make the switch?

2023-11-25 23:58 UTC, airidaceae commented on plugins/time/src/lib.rs
> +            debug!("sleep request has reply address");
I thought I saw different in the window pr. Let me pull up the code real quick.

2023-11-25 23:59 UTC, airidaceae commented on plugins/time/src/lib.rs
> +            debug!("sleep request has reply address");
```rs
 Ok(data) => data,
            Err(err) => {
                let name = std::any::type_name::<T>();
                error!("error deserializing {}: {:?}", name, err);
```

2023-11-26 00:00 UTC, airidaceae commented on plugins/time/src/lib.rs
> +            debug!("sleep request has reply address");
This seemed similar enough in my mind.

2023-11-26 00:00 UTC, marceline-cramer commented on plugins/time/src/lib.rs
> +            debug!("sleep request has reply address");
It is; seems like a mistake on my part in the window PR.

2023-11-26 00:01 UTC, airidaceae commented on plugins/time/src/lib.rs
> +            debug!("sleep request has reply address");
Ok. Ill add comments to change it there then

2023-11-29 03:48 UTC, airidaceae approved these changes

2023-11-29 04:00 UTC, merged