Kindling host api
hearth-rs/hearth pull request #252
Opened 2023-11-29 05:42 UTC by airidaceae

Still need to implement:
- [ ] fs
- [ ] time
- [ ] canvas
- [ ] terminal
- [ ] window
- [ ] debug draw

Other misc TODO
- [ ] turn wasm `spawn_fn` and `spawn_mod` functions into methods
- [ ] clean up pub use statements for easy importing

2023-12-09 22:11 UTC, marceline-cramer commented
Gonna need to merge main after #254.

2023-12-12 07:12 UTC, marceline-cramer commented on kindling/host/src/fs.rs
> +pub struct Filesystem {
Could you make `Filesystem` a type alias for a monomorphized `RequestResponse` instead? It'll save you the `request()` implementation and be more idiomatic.

2023-12-12 07:12 UTC, marceline-cramer commented on kindling/host/src/fs.rs
> +    pub fn list_files(&self, path: &str) -> Result<Vec<FileInfo>, Error> {
Glorious.

2023-12-12 07:13 UTC, marceline-cramer commented on kindling/init/src/lib.rs
> +    for file in fs.list_files(search_dir).unwrap() {
This is where Freja would say something like, "it can't possibly be that simple, right?"

2023-12-12 07:14 UTC, marceline-cramer commented on kindling/host/src/fs.rs
> +            _ => panic!("expected Success::Get, got {:?}", success),
Introduce a new `MalformedResponse` error type or something like that to handle this case.

2023-12-12 07:16 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +    /// Spawns a child process for the given function.
Zap.

2023-12-12 07:16 UTC, marceline-cramer commented on kindling/host/src/lib.rs
> +use std::marker::PhantomData;
License header.

2023-12-13 00:52 UTC, airidaceae commented on kindling/host/src/fs.rs
> +pub struct Filesystem {
Making this into a lazystatic instead

2023-12-13 21:59 UTC, airidaceae commented
I am removing the Result return types for the type being because clippy is complaining and they are pretty much entirely unused right now.

2023-12-14 01:19 UTC, marceline-cramer commented
Closes #214, closes #236.

2023-12-14 02:58 UTC, marceline-cramer requested changes
A few minor nitpicks but generally wonderful, wonderful work.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/Cargo.toml
> +edition = "2021"
Needs a `license` field.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/Cargo.toml
> +# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
Zap.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/src/fs.rs
> +    /// A lazily-initialized handle to the Filesystem service.
We can zap this.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/src/fs.rs
Needs docs comments on all functions.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/src/terminal.rs
> +// This may change, depends on https://github.com/hearth-rs/hearth/issues/189
It actually won't, sorry. That issue works the other way around; notifying terminal owners when their terminals have exited.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/src/wasm.rs
> +    /// A lazily-initialized handle to the WebAssembly spawner service.
Can zap this too.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/src/wasm.rs
> +    let entrypoint = cb as usize as u32;
didn't even know you could do this without transmuting it lmao

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/src/wasm.rs
> +pub fn spawn_mod(lump: LumpId, registry: Option<Capability>) -> Capability {
Doc comment.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/src/wasm.rs
> +/// Spawns a child process for the given function.
Explain the `registry` field.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/host/src/wasm.rs
> +pub fn spawn_mod(lump: LumpId, registry: Option<Capability>) -> Capability {
Also explain `registry`.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/init/src/lib.rs
So fucking cool.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/init/src/lib.rs
>  macro_rules! log {
Move this and the other variations of it into `kindling_host` and export in the prelude. Also implement the missing variations.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/services/terminal-demo/src/lib.rs
> +use kindling_host::{registry::REGISTRY, *};
Could you see if we could use only `kindling_host::prelude::*` here?

Also see if you can update this to use the terminal wrapper API.

2023-12-14 02:58 UTC, marceline-cramer commented on kindling/services/window-test/src/lib.rs
> +use kindling_host::registry::REGISTRY;
Use the window wrapper API in this module.

2023-12-14 03:55 UTC, airidaceae commented on kindling/init/src/lib.rs
i did not mean to change this file in this commit but eh its fine. it happens

2023-12-14 04:46 UTC, marceline-cramer requested changes
Almost done...

2023-12-14 04:46 UTC, marceline-cramer commented on kindling/host/src/macros.rs
I think this should be moved to the bottom of `lib.rs` instead. It's missing a license header anyways.

2023-12-14 04:58 UTC, marceline-cramer approved these changes
fuck yeah

2023-12-14 05:01 UTC, merged