Route process logs through tracing
hearth-rs/hearth pull request #274
Opened 2023-12-30 22:11 UTC by ten3roberts

Resolves: #209 #205

2023-12-30 22:20 UTC, ten3roberts commented
Example:
![image](https://github.com/hearth-rs/hearth/assets/25723553/c4653e04-028a-43e5-b873-70423c383a32)

2024-01-09 01:12 UTC, airidaceae commented
ooooh this looks really good

2024-01-09 07:55 UTC, ten3roberts commented
Thank you ❤️

@marceline-cramer, do you mind giving this a review, and I'll bring the branch up to date?

2024-01-10 23:44 UTC, marceline-cramer requested changes
Only have a couple minor things to whine about code-wise. Great work!

2024-01-10 23:44 UTC, marceline-cramer commented on core/runtime/src/process.rs
> +    pub process_span: Span,
This seems like a really good way to keep track of this. One thing I'm curious about though is how do we intercept the process events through the debugging infrastructure?

2024-01-10 23:44 UTC, marceline-cramer commented on core/runtime/src/runtime.rs
> +            process.spawn(name, runtime, ctx);
Really happy to see how much code this cleans up.

2024-01-10 23:44 UTC, marceline-cramer commented on core/runtime/src/runtime.rs
> +        registry_inner.spawn("Registry".to_string(), runtime.clone(), registry);
Ditto for here.

2024-01-10 23:44 UTC, marceline-cramer commented on core/runtime/src/utils.rs
> +        token: ProcessRunToken,
I didn't like this the first time I saw it because I was concerned about increasing the API surface area of this trait function but after reconsidering I realized that we should rarely be implementing this manually, so now I think that this is a really elegant way to keep people from directly calling this function.

2024-01-10 23:44 UTC, marceline-cramer commented on core/runtime/src/utils.rs
> +        let span = ctx.borrow().borrow_info().process_span.clone();
Gorgeous.

2024-01-10 23:44 UTC, marceline-cramer commented on core/runtime/src/utils.rs
> +                debug!(name = label, "spawning service");
One minor nitpick: not every process is a service. Could we maybe change this to "Spawning Tokio thread", perhaps? @airidaceae may have a better idea

2024-01-10 23:44 UTC, marceline-cramer commented on core/schema/Cargo.toml
> +tracing = { workspace = true }
Was worried about this when I first saw this because I was concerned that adding this dep might blow up the sizes of our Wasm modules, but if `hearth-guest` is bringing it in anyways, that'll happen no matter what. I think that we should keep this for now and see if we can find opportunities to cut down on deps like these *if it becomes a problem*.

2024-01-10 23:44 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +    // initialize tracing subscriber
beautiful.

2024-01-10 23:44 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/subscriber.rs
> +// Copyright (c) 2023 the Hearth contributors.
This is exciting shit.

2024-01-10 23:44 UTC, marceline-cramer commented on kindling/services/window-test/src/lib.rs
> +        info!(?msg, "window event");
I like this syntax a lot, nice to see that it ends up looking so good in the log too.

2024-01-10 23:44 UTC, marceline-cramer commented on plugins/wasm/src/lib.rs
> +        info.process_span.in_scope(|| match level {
Sweeeeeeeeeeeet. Surprisingly elegant for the amount of debugging power this is leveraging.

2024-01-10 23:44 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/subscriber.rs
> +        // TODO: Support structured logging
We'll need to open a follow-up issue.

2024-01-10 23:44 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/subscriber.rs
> +        // TODO: Support structured logging
Actually, @ten3roberts, you'll know the best way to do this, like what sort of structuring we'd be doing this way, so before this PR gets merged, could you please open an issue?

2024-01-10 23:48 UTC, marceline-cramer commented
One other big thing I've noticed is that it seems like processes spawned by the Wasm process spawner are inheriting a portion of its span. There are two `process_id` and `label` fields in the tracing events, and those events also begin with `process:process:`. Is there anything we can do to fix that?

2024-01-11 19:50 UTC, ten3roberts commented
> One other big thing I've noticed is that it seems like processes spawned by the Wasm process spawner are inheriting a portion of its span. There are two `process_id` and `label` fields in the tracing events, and those events also begin with `process:process:`. Is there anything we can do to fix that?

You've got a keen eye, which is good.

The two process ids afe because this span method preserves the structure and nesting of processes. I.e; it supports subprocesses wherein a process spawned by another process will have a span which parent span is the parent process.

The current tracing formatter pushes all the span fields to the far right, in effect losing the span hierarchy.

This could be solved by using [`tracing-tree`](https://github.com/davidbarsky/tracing-tree), which will amke it easier to see the spans and logs as a nested structure.

In hearth, the two process spans are due to the WasmSpawner process that spawns the guest processes, if I recall correctly.

Let me know if you'd like me to explore different tracing subscriber formatters, or if you'd like me not to touch that ❤️

2024-01-11 19:58 UTC, ten3roberts commented on core/runtime/src/process.rs
> +    pub process_span: Span,
We can create a custom subscriber for that.

By using the `registry` in the `tracing-subscriber` which allows us to layer subscribers on top of each other

2024-01-13 19:32 UTC, marceline-cramer commented
Thanks for explaining what's going on!

The issue I see with this mode of displaying the layered process info is that it gives the wrong impression that processes are nested within each other or in a tree organizational structure. That might be a pretty common abstract design pattern in a lot of the guest-side code we write, but for now, structuring processes into trees isn't an explicit or concrete feature built into the process APIs. In this specific case, the Wasm spawner isn't really the "parent" of the processes it spawns either, since it immediately passes ownership of spawned processes to the processes that made the spawn request, which is abstractly "the parent".

I think that the best way to approach this for now is to keep every process in its own dedicated span that doesn't inherit anything from the process that spawned it directly or indirectly. We could maybe reflect some future process nesting info in the structuring of the logging in the future but that's going to be up to how exactly we decide to tackle that.

2024-01-13 23:12 UTC, ten3roberts commented
I see.

I can absolutely change that behavior and remove a process' awareness of the environment it was spawned in.

2024-01-16 22:46 UTC, ten3roberts commented on guest/rust/hearth-guest/src/subscriber.rs
> +        // TODO: Support structured logging
Done https://github.com/hearth-rs/hearth/issues/286 :heart:

2024-01-16 22:46 UTC, ten3roberts commented
Lovely people in my GitHub feed,

The aforementioned suggestions have now been fixed

2024-01-16 22:48 UTC, ten3roberts commented
![image](https://github.com/hearth-rs/hearth/assets/25723553/d6cc287b-a99a-48fb-b47e-0360f20f7068)

2024-01-17 03:47 UTC, marceline-cramer requested changes
This is looking *great*. One last thing and then it's good in my book.

2024-01-17 03:47 UTC, marceline-cramer commented on core/runtime/src/utils.rs
> +                debug!(name = label, "spawning service");
Actually, let's just remove this log message.

2024-01-17 20:40 UTC, airidaceae commented on core/runtime/src/utils.rs
> +                debug!(name = label, "spawning service");
Yeah I don't think that the log message is too necessary.

2024-01-17 21:00 UTC, airidaceae requested changes
I think that I would like a few more doc comments to make it a bit easier to understand but other than that its looking really good!

2024-01-18 22:40 UTC, ten3roberts commented on core/runtime/src/utils.rs
> +}
It is a pattern I've seen and used where you use a ZST struct as a *proof*/*token* that you can or have done something.

https://predr.ag/blog/definitive-guide-to-sealed-traits-in-rust/#sealing-traits-via-method-signatures

The token type has a private field such that it can not be constructed externally,but must come from e.g; the library or another trusted authorizer.

This allows you to enforce an invariant or some other property, and allows you to restrict certain functions to be called unless you obtain an instance of the token. A type level protection of "call permission" so to say.

In this case, it prevents code outside of this module from calling the `run` function, since they can't obtain the permission to do so. However, external code can still call `run` if they have a token, for example if you create a wrapper around a `ProcessRunner`, I.e; you can call `run` inside another call to `run` because you will then obtain that token. This enforces that all calls to `run` ultimately come from `spawn`, but does still allow for forwarding impls.

Glfw uses a token pattern to ensure you call the `init` function. https://docs.rs/glfw/latest/glfw/struct.Glfw.html.

You can do lots of fun stuff with this pattern.

By adding a phantom lifetime to it, you can restrict the function scope/time where you can call the restricted calls, and prevents you from storing the token for later use.

You can also mix that with consuming and non-consuming methods, to limit the number of times you can call a function. Since a ZST has no size, it is actually free to store it in a vector and won't cause an allocation, so you can have a vector of Tokens, where you can pop tokens off and call functions as needed while also allowing you to match/inspect how many calls you have remaining, compared to e.g a counter which you forget to check.

Hope that explains it a bit better

2024-01-20 21:28 UTC, airidaceae approved these changes

2024-01-20 21:28 UTC, airidaceae commented on core/runtime/src/utils.rs
> +}
That makes a lot of sense. The doc comments look great as well. Thank you!

2024-01-20 21:52 UTC, marceline-cramer approved these changes
Great work.

2024-01-20 21:52 UTC, merged