guest: change send/recv to be json by default and add send_raw/recv_raw
hearth-rs/hearth pull request #279
Opened 2024-01-04 21:06 UTC by Meister1593

Resolves  https://github.com/hearth-rs/hearth/issues/278

My first pr, please read it thoroughly, i probably didn't know what i was doing

2024-01-05 09:23 UTC, Meister1593 commented
huh, rustfmt really wants to reformat it differently

does it take configuration from elsewhere?...

2024-01-06 18:42 UTC, airidaceae commented
Been pretty busy recently. Hoping to find some time to look through this today

2024-01-08 05:00 UTC, marceline-cramer commented
I figure that CI is going off on us because it's using nightly rustfmt. I'll experiment with it locally to see if it's still necessary. I think we were originally using nightly rustfmt so that it could properly format `let Some(x) = something else { ... };` syntax.

2024-01-09 01:06 UTC, airidaceae commented
The kindling CI is in a different workspace so you just needed to run `cargo fmt` within the kindling directory.

2024-01-09 01:09 UTC, airidaceae requested changes
This PR looks really good so far! I think we should be good to go after we fix up `try_recv`

2024-01-09 01:09 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
`try_recv` has not been changed at all. Honestly I'm not too sure what the use case is @marceline-cramer can you elaborate on what you wanted to be done with it when you mentioned it in #278

2024-01-09 01:16 UTC, Meister1593 commented on guest/rust/hearth-guest/src/lib.rs
Oh. Honestly didnt even notice I missed that one... Will check as well what I can do with it, but all I see for now is renaming it to `try_recv_signal`, since there is no json counterpart? Or maybe adding json too...
Will need clarification around that

2024-01-09 01:19 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
yeah that's not really clarification I can give. Id leave it as is for now and see what Marceline thinks.

2024-01-10 23:23 UTC, marceline-cramer requested changes
Other than the stuff with `try_recv` this looks absolutely fantastic. Props for updating all of the code using these functions, too.

2024-01-10 23:23 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
Yeah, not doing JSON deserialization in `try_recv` was an oversight on my part, and that's made it a little harder to do things like solve the UI latency accumulation issue. I think that `try_recv`, `try_recv_raw`, and `try_recv_signal` will be the best approach.

2024-01-10 23:23 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +    /// Sends a type, serialized as JSON, to this capability.
Love it.

2024-01-10 23:23 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +    pub fn send_raw(&self, data: &[u8], caps: &[&Capability]) {
Love it.

2024-01-10 23:23 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +    pub fn recv_signal(&self) -> Signal {
+1 for that

2024-01-10 23:23 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +    pub fn recv_raw(&self) -> (Vec<u8>, Vec<Capability>) {
Beautiful.

2024-01-11 00:21 UTC, Meister1593 commented
Added remaining try_recv stuff, check whenever you're feel comfortable and i think that's it for pr?

2024-01-11 00:24 UTC, Meister1593 commented
Added two todo's that you might want to look at

2024-01-12 16:03 UTC, airidaceae requested changes

2024-01-12 16:05 UTC, Meister1593 commented on guest/rust/hearth-guest/src/lib.rs
> +                // todo: u32::MAX could be replaced by const indicating invalid handle?
i thought it's something that is gonna be used more than once, but if not i'm just gonna explain it in comment ye
=

2024-01-13 19:38 UTC, marceline-cramer requested changes
Looking great, just a couple nitpicks and a discussion to resolve with @airidaceae.

2024-01-13 19:38 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +    /// and return None if there was no signal or it was down.
+1. Little tricky of a distinction, can't blame you for missing this.

2024-01-13 19:38 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +        let data = serde_json::from_slice(&msg.0).unwrap(); // todo: result type could be made into result with error handling
I disagree. The `None` value is already semantically overloaded with the mailbox being empty. If a message fails to deserialize, the process should log an error and die, observing "fail fast" principles.

2024-01-13 19:38 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +        let Some(msg) = msg else {
Here, you can use the question mark operator to automatically return `None` if `try_recv_raw()` returns `None`, instead of manually extracting the `Some` case.

2024-01-13 19:38 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +                // todo: u32::MAX could be replaced by const indicating invalid handle?
It is something that's going to be used more than once, but in my opinion `u32::MAX` is already a damn good constant to use here, given the context of its use as a handle where `0` is valid.

2024-01-13 19:59 UTC, Meister1593 commented on guest/rust/hearth-guest/src/lib.rs
> +        let data = serde_json::from_slice(&msg.0).unwrap(); // todo: result type could be made into result with error handling
left as is for now

2024-01-13 20:00 UTC, Meister1593 commented on guest/rust/hearth-guest/src/lib.rs
> +    /// and return None if there was no signal or it was down.
updated doc

2024-01-13 20:00 UTC, Meister1593 commented on guest/rust/hearth-guest/src/lib.rs
> +        let data = serde_json::from_slice(&msg.0).unwrap(); // todo: result type could be made into result with error handling
will keep in mind!

2024-01-13 20:02 UTC, Meister1593 commented on guest/rust/hearth-guest/src/lib.rs
> +        let Some(msg) = msg else {
thanks, it simplified code quite a bit

2024-01-17 05:40 UTC, marceline-cramer reviewed
Final note. After this is fixed we should be fine to merge.

2024-01-17 05:40 UTC, marceline-cramer commented on guest/rust/hearth-guest/src/lib.rs
> +        if let Some(Signal::Message(msg)) = signal {
Roux and I talked about this in private and this should panic if it receives a down signal, just like `recv` and `recv_raw` do.

2024-01-17 20:29 UTC, airidaceae commented on guest/rust/hearth-guest/src/lib.rs
> +        let data = serde_json::from_slice(&msg.0).unwrap(); // todo: result type could be made into result with error handling
I think I agree with Marceline. I dont think there's a case where we would want to recover from that error so its probably best to just fail.

2024-01-18 21:13 UTC, marceline-cramer approved these changes
Awesome!

2024-01-20 21:21 UTC, airidaceae approved these changes

2024-01-20 21:22 UTC, merged