readme: Running instructions
hearth-rs/hearth pull request #298
Opened 2024-01-24 23:58 UTC by airidaceae

closes #231
depends on #297

2024-01-25 18:18 UTC, marceline-cramer requested changes
minor feedback.

2024-01-25 18:18 UTC, marceline-cramer commented on README.md
> +cargo alias is provided for ease of use.
```suggestion
and init system can be built with the script found in the tools directory.

A Cargo alias is provided for ease of use:
```

2024-01-25 18:18 UTC, marceline-cramer commented on README.md
> +following command in the root of the repository.
```suggestion
Now that the root has been built, Hearth can be ran with Kindling as its root:
```

2024-01-25 18:18 UTC, marceline-cramer commented on README.md
> +and can be found in the [corresponding directory](./kindling). Kindling's root
Adapt how you want to fit the formatting you'd like.

```suggestion
the init system and a directory to serve as its root. Hearth provides a set of
batteries-included utilities for use with the runtime, named Kindling.
Kindling's source code is located within this repository [here](./kindling). Kindling's root
```

2024-01-25 20:31 UTC, airidaceae commented on README.md
> +following command in the root of the repository.
This was meant to state that this command only works when in the root of the repository.

2024-01-25 20:37 UTC, airidaceae commented on README.md
> +and can be found in the [corresponding directory](./kindling). Kindling's root
making some bigger changes to this paragraph. Let me know what you think.

2024-01-26 01:09 UTC, marceline-cramer commented on README.md
> +following command in the root of the repository.
The runtime's filesystem root vs the repository root is ambiguous, could you suggest a better way of conveying that?

2024-01-26 06:39 UTC, airidaceae commented on README.md
> +following command in the root of the repository.
Honestly I think that my original clarification wasnt actually all that necessary.

2024-01-27 02:44 UTC, marceline-cramer approved these changes

2024-01-27 03:52 UTC, merged